version: "3.8"
services:
  blog-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
  # mysql:
  #   image: mysql:5.7
  #   env_file:
  #     - ./env/mysql.env
